# Usa una imagen base de .NET
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

# Copia los archivos del proyecto y restaura las dependencias
COPY *.csproj ./
RUN dotnet restore

# Copia todo el código y publica
COPY . ./
RUN dotnet publish -c Release -o out

# Crea una imagen final de ejecución
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/out ./
ENTRYPOINT ["dotnet", "PeticionesAPI.dll"]