// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeticionesAPI.Data;

#nullable disable

namespace PeticionesAPI.Migrations
{
    [DbContext(typeof(PeticionesDbContext))]
    [Migration("20250826175744_CambiarNombreTabla")]
    partial class CambiarNombreTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeticionesAPI.Models.Peticion", b =>
                {
                    b.Property<int>("PeticionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeticionID"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreOpcional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeticionTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeticionID");

                    b.ToTable("Peticiones");
                });
#pragma warning restore 612, 618
        }
    }
}
